# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
