# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured',
            field=models.NullBooleanField(),
        ),
    ]
