# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=9)),
                ('image', models.ImageField(upload_to='img')),
                ('urlpath', models.CharField(max_length=200)),
                ('button', models.CharField(max_length=100)),
                ('headline_alignment', models.CharField(choices=[('slider-left-aligned', 'Left Aligned'), ('slider-right-aligned', 'Right Aligned')], default='slider-left-aligned', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
