# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslider',
            name='headline_alignment',
            field=models.CharField(choices=[('slider-left-aligned', 'Left Aligned'), ('slider-center-aligned', 'Center Aligned'), ('slider-right-aligned', 'Right Aligned')], default='slider-left-aligned', max_length=50),
        ),
    ]
