# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-29 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepageslider_headline_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslider',
            name='headline_alignment',
            field=models.CharField(choices=[('slider-left-aligned', 'Left Aligned'), ('slider-right-aligned', 'Right Aligned')], default='slider-left-aligned', max_length=50),
        ),
    ]
