# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('voucher', 'Gift Voucher'), ('workshop', 'Workshop'), ('class', 'Class'), ('product', 'Product')], default='product', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=9)),
                ('image', models.ImageField(upload_to='img')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('workshop_start_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('workshop_end_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('workshop_start_time', models.TimeField(blank=True)),
                ('workshop_end_time', models.TimeField(blank=True)),
                ('available_places', models.IntegerField(default=10)),
                ('workshop_location', models.CharField(choices=[('headford', 'Headford Wellbeing Centre'), ('burren', 'Burren')], default='Headford Wellbeing Centre', max_length=940)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_products.product_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
