# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-29 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_location',
            field=models.CharField(choices=[('headford', 'Headford Wellbeing Centre'), ('burren', 'Burren')], default='headford', max_length=940),
        ),
    ]
